//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessagingService.API.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MessagingService.API.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kullanıcı adı veya e-mail adresiyle ile sistemde kayıt mevcuttur..
        /// </summary>
        internal static string FoundUserErrorMsg {
            get {
                return ResourceManager.GetString("FoundUserErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen giriş yapınız..
        /// </summary>
        internal static string LoginErrorMsg {
            get {
                return ResourceManager.GetString("LoginErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Error.
        /// </summary>
        internal static string LoginStatusErrorMsg {
            get {
                return ResourceManager.GetString("LoginStatusErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Success.
        /// </summary>
        internal static string LoginStatusSuccessMsg {
            get {
                return ResourceManager.GetString("LoginStatusSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout Success.
        /// </summary>
        internal static string LogOutSuccessMsg {
            get {
                return ResourceManager.GetString("LogOutSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistemde kullanıcı bilgisi bulunamadı..
        /// </summary>
        internal static string NotFoundUserMsg {
            get {
                return ResourceManager.GetString("NotFoundUserMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daha önceden aynı kayıt yapılmıştır..
        /// </summary>
        internal static string ReplaceDataMsg {
            get {
                return ResourceManager.GetString("ReplaceDataMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt sırasında bir hata oluştu..
        /// </summary>
        internal static string SaveErrorMsg {
            get {
                return ResourceManager.GetString("SaveErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem başarılı..
        /// </summary>
        internal static string SuccessMsg {
            get {
                return ResourceManager.GetString("SuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem yapılan kullanıcı sistemde tanımlı değildir..
        /// </summary>
        internal static string TransactionUserNotFoundMsg {
            get {
                return ResourceManager.GetString("TransactionUserNotFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beklenmedik bir hata oluştu..
        /// </summary>
        internal static string UnexpectedErrorMsg {
            get {
                return ResourceManager.GetString("UnexpectedErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bilgileri eksiksiz doldurunuz..
        /// </summary>
        internal static string ValidErrorMsg {
            get {
                return ResourceManager.GetString("ValidErrorMsg", resourceCulture);
            }
        }
    }
}
